### ISSUE TITLE
Crash when selecting Lutris

### ISSUE THREAD

**Issue by GitEz-code** [RobLoach/lutris-kodi-addon#59]
Whether I use the zip file or from the repository, kodi crashes when I select lutris. version 0.5.9.1 of lutris is installed. here are the crash logs:

```
021-12-30 16:08:21.720 T:46483    INFO <general>: Loading skin file: MyGames.xml, load type: KEEP_IN_MEMORY
2021-12-30 16:08:21.788 T:46518    INFO <general>: initializing python engine.
2021-12-30 16:08:21.817 T:46518   ERROR <general>: Exception ignored deletion of interned string failed
2021-12-30 16:08:21.817 T:46518   ERROR <general>: :
                                                   
2021-12-30 16:08:21.817 T:46518   ERROR <general>: Traceback (most recent call last):
                                                   
2021-12-30 16:08:21.817 T:46518   ERROR <general>:   File "/usr/lib/python3.10/sqlite3/dbapi2.py", line 83, in register_adapters_and_converters
                                                   
2021-12-30 16:08:21.817 T:46518   ERROR <general>:     
2021-12-30 16:08:21.817 T:46518   ERROR <general>: register_converter("timestamp", convert_timestamp)
2021-12-30 16:08:21.817 T:46518   ERROR <general>: 
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: KeyError
2021-12-30 16:08:21.818 T:46518   ERROR <general>: : 
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 'timepart_full'
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: Exception ignored deletion of interned string failed
2021-12-30 16:08:21.818 T:46518   ERROR <general>: :
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: Traceback (most recent call last):
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>:   File "/usr/lib/python3.10/sqlite3/dbapi2.py", line 83, in register_adapters_and_converters
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>:     
2021-12-30 16:08:21.818 T:46518   ERROR <general>: register_converter("timestamp", convert_timestamp)
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: KeyError
2021-12-30 16:08:21.818 T:46518   ERROR <general>: : 
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 'timepart'
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: Exception ignored deletion of interned string failed
2021-12-30 16:08:21.818 T:46518   ERROR <general>: :
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: Traceback (most recent call last):
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>:   File "/usr/lib/python3.10/sqlite3/dbapi2.py", line 83, in register_adapters_and_converters
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>:     
2021-12-30 16:08:21.818 T:46518   ERROR <general>: register_converter("timestamp", convert_timestamp)
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: KeyError
2021-12-30 16:08:21.818 T:46518   ERROR <general>: : 
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 'datepart'
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: Exception ignored deletion of interned string failed
2021-12-30 16:08:21.818 T:46518   ERROR <general>: :
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: Traceback (most recent call last):
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: KeyError
2021-12-30 16:08:21.818 T:46518   ERROR <general>: : 
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 'convert_timestamp'
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: Exception ignored deletion of interned string failed
2021-12-30 16:08:21.818 T:46518   ERROR <general>: :
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: Traceback (most recent call last):
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: KeyError
2021-12-30 16:08:21.818 T:46518   ERROR <general>: : 
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 'convert_date'
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: Exception ignored deletion of interned string failed
2021-12-30 16:08:21.818 T:46518   ERROR <general>: :
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: Traceback (most recent call last):
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: KeyError
2021-12-30 16:08:21.818 T:46518   ERROR <general>: : 
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 'adapt_datetime'
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: Exception ignored deletion of interned string failed
2021-12-30 16:08:21.818 T:46518   ERROR <general>: :
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: Traceback (most recent call last):
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
                                                   
2021-12-30 16:08:21.818 T:46518   ERROR <general>: KeyError
2021-12-30 16:08:21.818 T:46518   ERROR <general>: : 
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 'adapt_date'
2021-12-30 16:08:21.818 T:46518   ERROR <general>: 
```

**Comment by GittiMcHub** [comment]
Hey @solbero, 
I freshly installed kodi 19 on a Ubuntu Desktop 20.04 LTS and it crashes when selecting Lutris.
I can shortly see an update Window(? idk, I'm new to lutris too) then the Ubuntu Crash Reporter opens.
Starting Lutris without Kodi works fine.

I start Kodi from the command line and this is the output:

```
libva info: VA-API version 1.12.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_12
ATTENTION: default value of option mesa_glthread overridden by environment.
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
libva info: va_openDriver() returns 0
ATTENTION: default value of option mesa_glthread overridden by environment.
sh: 1: nmblookup: not found
sh: 1: nmblookup: not found
ATTENTION: default value of option mesa_glthread overridden by environment.
2022-02-04 21:12:04,893: Starting Lutris 0.5.9.1
2022-02-04 21:12:04,918: No cores found
2022-02-04 21:12:05,528: Startup complete
2022-02-04 21:12:05,529: Running AMD Mesa driver 21.3.5 on AMD RENOIR (DRM 3.41.0, 5.13.0-28-generic, LLVM 13.0.0) (0x1638)
2022-02-04 21:12:05,530: GPU: 1002:1638 1002:1636 (amdgpu drivers)
ATTENTION: default value of option mesa_glthread overridden by environment.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 342, in do_command_line
    self.print_game_json(command_line, game_list)
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 580, in print_game_json
    games = [
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 588, in <listcomp>
    "playtime": str(timedelta(hours=game["playtime"])),
TypeError: unsupported type for timedelta hours component: NoneType
2022-02-04 21:12:05,651: Shutting down Lutris
```


What is interesting: When I start Lutris first and then go to Kodi, it just loads forever and nothing happens. The output in the terminal is empty, not even "Starting Lutris" appears.

Shall I create a separate ticket? 

And do you have a clue what could be the root of the problem? Maybe I can take a look into that?  
(Never wrote a Kodi Addon and Python is my least favorite, but I'm interested in getting it working again...)

**Comment by solbero** [comment]
The problem is with Lutris and not the add-on. The [issue is fixed](https://github.com/lutris/lutris/pull/3796) in the Lutris master branch. The best solution for now is to git clone the Lutris repository. Then in the add-on settings enable the setting to use a custom executable and point it to the git Lutris executable.

**Comment by GittiMcHub** [comment]
Works perfectly, thanks!
