### ISSUE TITLE
Lutris dosent launch

### ISSUE THREAD

**Issue by NishantMajumdar** [RobLoach/lutris-kodi-addon#64]
Lutris dosent launch

```
2023-06-14 12:51:36.953 T:7650    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: invalid syntax (lutris.py, line 44)
                                                   Traceback (most recent call last):
                                                     File "/home/nishant/.kodi/addons/plugin.lutris/addon.py", line 7, in <module>
                                                       from lib import router
                                                     File "/home/nishant/.kodi/addons/plugin.lutris/lib/router.py", line 15, in <module>
                                                       import lib.lutris as lutris
                                                     File "/home/nishant/.kodi/addons/plugin.lutris/lib/lutris.py", line 44
                                                       raise ValueError(f"Executable 'lutris' not in custom path '{result}'")
                                                                                                                           ^
                                                   SyntaxError: invalid syntax
                                                   -->End of Python script error report<--
                                                   
                                                   
```

**Comment by samuelmarinsoto** [comment]
I had this happen (or something similar) when using a script to launch lutris. I had to rename the script to `lutris` and change the custom path to it.

For some reason the `_get_path()` function in `lutris.py` checks that the executable is named `lutris`
